### ISSUE TITLE
Windows 10 display scale 

### ISSUE THREAD

**Issue by Bikeman868** [fallahn/crogine#101]
I just purchased the game on Steam and installed on Windows 10 Microsoft Surface Pro 4.

I went into the game settings and set the resolution to slightly less than my screen resolution, and the game became much larger then the screen, the menu disappeared off the bottom of the screen and I could no longer navigate to change the resolution back. I tried quitting the game with Alt-F4 and restarting it, but it remembered the resolution. I thought I was going to have to uninstall/reinstall to fix it.

I double checked my screen resolution in the Windows 10 display settings, and noticed that the scale was set to 225%. I tried reducing this to 100% and now the game fitted on the screen and became playable again.

I think your game should either ignore the display scaling, or take it into account when presenting the resolution options. Right now it's very easy to get stuck in a place where the game is unusable and the solution is not obvious.

**Comment by fallahn** [comment]
Hi! Sorry about this - I've never used screen scaling before so I had no idea it was an issue. I'll happily look into remedying it 😁

For future reference, if you have any issues with the game, specifically on Steam, could you leave them on the Steam discussions please? https://steamcommunity.com/app/2173760/discussions/ I monitor those more closely and will be able to give a faster response, thanks!
