### ISSUE TITLE
Particle System

### ISSUE THREAD

**Issue by zerodarkzone** [fallahn/crogine#90]
Hi,
Does the particle system works with an ortographic camera?

I've been trying to use the particle system with a 2d game but I'm not able to render any particles.

**Comment by zerodarkzone** [comment]
I was able to make it work by setting the z value of the emiter to a negative value

**Comment by fallahn** [comment]
It's probably getting culled from the frustum - you could also try setting the near plane of the orthographic view to < 0. However by default the draw order of 2D scenes is sorted by depth, so you'll probably want to be setting the z-value manually anyway 😁

Particles also use metres as the default unit in 3D so if you're using pixels as the units in 2D you might need to scale up the size of the particles. crogine can load particle settings made for xygine, so you can use the [xygine particle editor](https://github.com/fallahn/xygine/tree/master/SimpleParticleEditor) to create presets.
