### ISSUE TITLE
How does the Sprite Editor Work?

### ISSUE THREAD

**Issue by zerodarkzone** [fallahn/crogine#93]
Hi,
I'm trying to use the sprite editor to generate a sprite sheet but it does not render anything,

![image](https://github.com/fallahn/crogine/assets/22160983/9f7a9bb5-2873-424c-9404-74eb97a33e98)

Do you have a way of creating sprite sheets? the format is quite custom.

**Comment by fallahn** [comment]
You probably need to set your working directory so that the editor knows the relative path to load the assets. Go to View->Options then browse to the directory where you keep the assets directory

**Comment by zerodarkzone** [comment]
Thanks
