### ISSUE TITLE
Flip 2D Sprite

### ISSUE THREAD

**Issue by zerodarkzone** [fallahn/crogine#98]
Hi, 
In xygine it was possible to flip a sprite by setting the transform to a negative number. When I try to do the same in crogine, the sprite disappears.

Thanks

**Comment by fallahn** [comment]
You need to tell the Drawable2D component that you've flipped the sprite, so that it can correct the vertex winding. See here: https://github.com/fallahn/crogine/blob/master/crogine/include/crogine/ecs/components/Drawable2D.hpp#L260

**Comment by zerodarkzone** [comment]
That works. Thank you
